### ISSUE TITLE
 I try upgraded many times, still can’t connect~

### ISSUE THREAD

**Issue by wetezwallet** [certusone/genki-3001#2]
gaiacli status
{“node_info”:{“protocol_version”:{“p2p”:“5”,“block”:“8”,“app”:“0”},“id”:“dd3ac2ebe1df9ce3e4cfc39324d1e249e13e3d3a”,“listen_addr”:“tcp://0.0.0.0:26656”,“network”:“genki-3001”,“version”:“0.27.0”,“channels”:“4020212223303800”,“moniker”:“wecosmos02”,“other”:{“tx_index”:“on”,“rpc_address”:“tcp://0.0.0.0:26657”}},“sync_info”:{“latest_block_hash”:"",“latest_app_hash”:"",“latest_block_height”:“0”,“latest_block_time”:“1970-01-01T00:00:00Z”,“catching_up”:true},“validator_info”:{“address”:“0077F68359FE12C678980AC3442460CB1CC1ABC4”,“pub_key”:{“type”:“tendermint/PubKeyEd25519”,“value”:“zf+aS3anGNm9CrpliDTqpUlHCBpi0qZknUo+aYOXC+s=”},“voting_power”:“0”}}

E[13126-12-13|02:59:31.897] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=aa3464017cd5abd9ff0204f2e161d66f9442db29@52.53.197.37:26656 elapsed=2m15.618889075s
E[13126-12-13|02:59:45.042] Dialing failed module=pex addr=f7290d305237b3fef01a59a4919aa6b399234983@35.183.126.181:26656 err=“dial tcp 35.183.126.181:26656: i/o timeout” attempts=3
E[13126-12-13|03:00:14.216] Dialing failed module=pex addr=6a04069a2736f096404df2bbc31d7c2807c080c0@13.56.78.160:26656 err=“dial tcp 13.56.78.160:26656: connect: connection refused” attempts=5
E[13126-12-13|03:00:14.217] Dialing failed module=pex addr=aa3464017cd5abd9ff0204f2e161d66f9442db29@52.53.197.37:26656 err=“dial tcp 52.53.197.37:26656: connect: connection refused” attempts=5
E[13126-12-13|03:00:14.276] Dialing failed module=pex addr=a966b0806aca7e62d5c43d8bd09425aecdcf44f2@35.182.242.163:26656 err=“dial tcp 35.182.242.163:26656: connect: connection refused” attempts=5
E[13126-12-13|03:00:15.042] Dialing failed module=pex addr=f7290d305237b3fef01a59a4919aa6b399234983@35.183.126.181:26656 err=“dial tcp 35.183.126.181:26656: i/o timeout” attempts=4
E[13126-12-13|03:01:15.044] Dialing failed module=pex addr=f7290d305237b3fef01a59a4919aa6b399234983@35.183.126.181:26656 err=“dial tcp 35.183.126.181:26656: i/o timeout” attempts=5
E[13126-12-13|03:01:44.216] Dialing failed module=pex addr=6a04069a2736f096404df2bbc31d7c2807c080c0@13.56.78.160:26656 err=“dial tcp 13.56.78.160:26656: connect: connection refused” attempts=6
E[13126-12-13|03:01:44.217] Dialing failed module=pex addr=aa3464017cd5abd9ff0204f2e161d66f9442db29@52.53.197.37:26656 err=“dial tcp 52.53.197.37:26656: connect: connection refused” attempts=6
E[13126-12-13|03:01:44.276] Dialing failed module=pex addr=a966b0806aca7e62d5c43d8bd09425aecdcf44f2@35.182.242.163:26656 err=“dial tcp 35.182.242.163:26656: connect: connection refused” attempts=6

**Comment by leoluk** [comment]
Please try again with the new set of seed nodes.
